name: MiApp
options:
  bundleIdPrefix: com.xitfarge
  deploymentTarget:
    iOS: "14.0"
targets:
  MiApp:
    type: application
    platform: iOS
    sources:
      - path: MiApp
    settings:
      base:
        INFOPLIST_FILE: MiApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.xitfarge.app
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
